[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "FanDao"
authors = [{name = "Hank Zimmer", email = "baticsea@protonmail.com"}]
dynamic = ["version", "description"]
